### ISSUE TITLE
Test fails if it is in a monorepo sub-project

### ISSUE THREAD

**Issue by ErynManela** [lilbaek/webstorm-testcafe#4]
If you have a lerna monorepo style project

root 
       /node_modules
       /projects
                     /mytestingproject
                                                 /tests
                                                        /kindsoftests
                                                               |_mytest.ts
                                                /config
                                                        |_config.json 
                                                /node_modules
and you try to run a test, you get the following error:

```
Testing started at 3:53 PM ...
Testing started at 3:53 PM ...
"C:\Program Files\nodejs\node.exe" --inspect-brk=56177 node_modules/testcafe/lib/cli/index.js chrome C:/Users/user/projects/myproject/projects/e2e-ui/tests/common/my-tests.ts -r spec,json:node_modules/testcafe/tmp/testcafe-out-a8ce8b07-162a-476b-aa83-2d5daf9548ac --color
Debugger listening on ws://127.0.0.1:56177/8e3f776f-b91e-48f0-b8c7-5a0a64b0d655
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Running on [local] environment
Reading configuration file [config/config.json]...
ERROR Cannot prepare tests due to an error.

Error: ENOENT: no such file or directory, open 'config/config.json'
    at Function.read (C:\Users\username\projects\myproject\node_modules\ui-e2e-framework\src\utils\files.ts:17:15)
    at Object.<anonymous> (C:\Users\user\projects\myproject\node_modules\ui-e2e-framework\src\config\config.ts:21:72)
    at Object.origExt [as .js] (C:\Users\user\projects\myproject\node_modules\testcafe\src\compiler\test-file\api-based.js:83:21)
    at Object.<anonymous> (C:\Users\user\projects\myproject\node_modules\ui-e2e-framework\src\ui\e2e-ui-test-suite.ts:2:1)
    at Object.origExt [as .js] (C:\Users\user\projects\myproject\node_modules\testcafe\src\compiler\test-file\api-based.js:83:21)
    at Object.<anonymous> (C:\Users\user\projects\myproject\projects\e2e-ui\tests\common\bind-io-flow-tests.ts:3:1)
    at Function._compile [as _execAsModule] (C:\Users\user\projects\myproject\node_modules\testcafe\src\compiler\test-file\api-based.js:50:13)
    at TypeScriptTestFileCompiler._execAsModule [as _runCompiledCode] (C:\Users\user\projects\myproject\node_modules\testcafe\src\compiler\test-file\api-based.js:149:42)
    at TypeScriptTestFileCompiler._runCompiledCode [as execute] (C:\Users\user\projects\myproject\node_modules\testcafe\src\compiler\test-file\api-based.js:173:21)
    at execute (C:\Users\user\projects\myproject\node_modules\testcafe\src\compiler\index.js:96:35)

Type "testcafe -h" for help.
Waiting for the debugger to disconnect...

Process finished with exit code 1
```

could you add a path to config option for the plugin?

**Comment by lilbaek** [comment]
I released a new version with this functionality yesterday but it is currently pending approval by Jetbrains.
![image](https://user-images.githubusercontent.com/3147748/69696181-2c95fd00-10df-11ea-9659-6ee61368d296.png)
If the new version (When approved) does not solve your issue please provide a small repo.
Thanks.
